### PR TITLE
Added "channels", lots of comments and such

### PR DESCRIPTION
**Pull request by ameshkov**
@gorhill please take a look.

### CODE REVIEW

**Comment by gorhill** [comment]
Looks good to me.

I gather that the `postMessage` solution works? In retrospect I see it's obvious, but I had not realized sending messages from web page to content script would work since they share the same `window` object (though each environment have their own copies of properties). In light of this, we could just drop the `Image` trick (less code = better)? The sole purpose was to establish some sort of communication with the background page, but now I would rather rely on the cleaner message sending approach.

**Comment by gorhill** [comment]
With the message approach, couldn't a web page wanting to defuse the blocking of websocket connections listen for messages send by the wrapper, and send back fake response authorizing the connection?

**Comment by ameshkov** [comment]
> I gather that the postMessage solution works?

Yep, seems to be good.

> With the message approach, couldn't a web page wanting to defuse the blocking of websocket connections listen messages send by the wrapper, and send back fake response authorizing the connection?

Hm, I guess this is possible. To overcome this we could add some kind of a handshake on "messageChannel" initialization.

**Comment by ameshkov** [comment]
In fact I think we shouldn't bother until somebody figures out how to trick us.

When our code is executed in a page context, there are dozens of different ways to trick us whichever messaging approach we use. For instance, image approach may be tricked by overriding Image.prototype.onerror or Image.prototype.src, etc.

**Comment by gorhill** [comment]
> For instance, image approach may be tricked by overriding Image.prototype.onerror or Image.prototype.src, etc.

True enough.

If ever needed, I can see pretty straightforward solutions, based on using "template" in the script text, so that only the content script and page script know how to talk to each other.

**Pull request merged**
